In [1]:
import pandas as pd

data = pd.read_csv("dataset/mixed_data_preprocessed_emoji.csv")
data.dropna(inplace = True)
data

,User,Company
0,Way to drop the ball on customer service @1158...,@115820 I'm sorry we've let you down! Without ...
1,@AmazonHelp 3 different people have given 3 di...,@115820 We'd like to take a further look into ...
2,@115823 I want my amazon payments account CLOS...,@115822 I am unable to affect your account via...
3,@115828 How about you guys figure out my Xbox ...,@115826 I'm sorry for the wait. You'll receive...
4,@AmazonHelp @115826 Yeah this is crazy we’re l...,@115827 Thanks for your patience. ^KM
...,...,...
19294,@ChipotleTweets Fort Worth off heritage Trace :(,@157688 I'm reaching out to this location's le...
19295,@ChipotleTweets Slow down! Half/half rice shou...,@157689 Sorry for the trouble. What location w...
19296,"@ChipotleTweets 818 Howe St, Vancouver, BC. 12...",@157689 I'm sharing your concerns with their l...
19297,@ChipotleTweets I just got home from chipotle ...,@157690 I'd be disappointed too. Let a manager...
19298,#lifeisburritoful after a full day of #BlackFr...,@157692 Yay! I'll share some love with Abdulla...

In [2]:
from langdetect import detect
data_for_use = pd.DataFrame()

for index, row in data.iterrows():
    try:
        if(detect(row[0]) == 'en'):
            data_for_use = data_for_use.append(row, ignore_index = True)
    except:
        pass

In [3]:
data_for_use

,Company,User
0,@115820 I'm sorry we've let you down! Without ...,Way to drop the ball on customer service @1158...
1,@115820 We'd like to take a further look into ...,@AmazonHelp 3 different people have given 3 di...
2,@115822 I am unable to affect your account via...,@115823 I want my amazon payments account CLOS...
3,@115826 I'm sorry for the wait. You'll receive...,@115828 How about you guys figure out my Xbox ...
4,@115827 Thanks for your patience. ^KM,@AmazonHelp @115826 Yeah this is crazy we’re l...
...,...,...
18663,@157688 I'm reaching out to this location's le...,@ChipotleTweets Fort Worth off heritage Trace :(
18664,@157689 Sorry for the trouble. What location w...,@ChipotleTweets Slow down! Half/half rice shou...
18665,@157689 I'm sharing your concerns with their l...,"@ChipotleTweets 818 Howe St, Vancouver, BC. 12..."
18666,@157690 I'd be disappointed too. Let a manager...,@ChipotleTweets I just got home from chipotle ...
18667,@157692 Yay! I'll share some love with Abdulla...,#lifeisburritoful after a full day of #BlackFr...

In [4]:
data_for_use.to_csv('dataset/mixed_data_preprocessed_fixed.csv', index=False)